import json
from .Create_KPIs import melt_it, stat_func
from .Create_Output import gen_out


def run_summarise_pipeline(eval_table, zip_name):
    print(f"Running summarisation for: {zip_name}")
    d1_2 = melt_it(eval_table)
    
    (
    df, serve_won_single, serve_lost_single, return_won_single, return_lost_single, won_single, lost_single,
    rally_324_won_single, rally_324_lost_single, rally_5plus_won_single, rally_5plus_lost_single,
    totalserve_eff_single, return_eff_freq_single, rally_eff_freq_single, firstserverate_single,
    firstserve_eff_single, secondserve_eff_single, df_rate_single, secondserves_freq_single,
    crit_totalserve_freq_single, crit_1stserve_freq_single, noncrit_1stserve_freq_single,
    noncrit_totalserve_freq_single, breakball_allserves_single, breakball_1stserverate_single,
    deuce_allserves_freq_single, adv_allserves_freq_single, firstserves_freq_single,
    deuce_firstserves_rate_single, adv_firstserves_rate_single, firstserve_serveonly_freq_single,
    firstserve_serveFH_freq_single, firstserve_serveBH_freq_single, serveplusplayed_single,
    FH_of_ServePlus1_single, firstserve_serveFH_eff_single, BH_of_ServePlus1_single,
    firstserve_serveBH_eff_single, Slice_of_ServePlus1_single, firstserve_serveSlice_eff_single,
    secondserve_serveonly_freq_single, secondserve_serveFH_freq_single, secondserve_serveBH_freq_single,
    FH_of_ServePlus1_2nd_single, secondserve_serveFH_eff_single, BH_of_ServePlus1_2nd_single,
    secondserve_serveBH_eff_single, Slice_of_ServePlus1_2nd_single, secondserve_serveSlice_eff_single,
    firstreturn_rate_single, secondreturn_rate_single, secondreturns_freq_single, firstreturns_freq_single,
    firstreturn_eff_single, secondreturn_eff_single, Total_Returns_single, FH_Return_prop_single,
    BH_Return_prop_single, Slice_Return_prop_single, FirstReturn_FH_prop_single, FirstReturn_BH_prop_single,
    FirstReturn_Slice_prop_single, FirstReturn_FH_Eff_single, FirstReturn_BH_Eff_single,
    FirstReturn_Slice_Eff_single, SecondReturn_FH_prop_single, SecondReturn_BH_prop_single,
    SecondReturn_Slice_prop_single, SecondReturn_FH_Eff_single, SecondReturn_BH_Eff_single,
    SecondReturn_Slice_Eff_single, rally_points_single, rally_eff_single, rally_win_balance_single,
    rally_win_balance2_single, rally_length_single, All_shots_single, FH_prop_single, BH_prop_single,
    Slice_prop_single, Volley_prop_single, OH_prop_single, FH_eff_single, FH_shots_single,
    FH_WinBalance2_single, FH_WinBalance_single, BH_eff_single, BH_shots_single, BH_WinBalance2_single,
    BH_RallyRate_single, BH_WinBalance_single, Slice_eff_single, Slice_shots_single, Slice_LossRate_single,
    Slice_WinBalance2_single, firstserve_lost_single, firstserve_rally_single, firstserve_won_single,
    firstservesOnlyProp_single, dfs_single, secondServe_total_lostwinner_single,
    secondServe_total_lostforced_single, secondServe_total_lostmistake_single, secondserve_lost_single,
    crit_nonbreakball_allserves_single, crit_nonbreakball_1stserverate_single, firstreturn_lost_single,
    firstreturn_won_single, secondreturn_lost_single, secondreturn_won_single, secondreturn_rally_single,
    crit_1streturnHIT_freq_single, noncrit_1streturnHIT_freq_single, rally_prop_single, FH_ratio_single,
    BH_Slice_ratio_single, ptsplayed_single, Won_thru_Winner_single, Lost_thru_Mistake_single,
    firstServe_total_lostmistake_single, firstServe_total_rally_single, firstServe_total_wonwinner_single,
    deuce_firstServe_total_lostmistake_single, deuce_firstServe_total_rally_single,
    deuce_firstServe_total_wonwinner_single, deuce_firstserves_freq_single,
    adv_firstServe_total_lostmistake_single, adv_firstServe_total_rally_single,
    adv_firstServe_total_wonwinner_single, adv_firstserves_freq_single, secondServe_total_rally_single,
    secondServe_total_wonwinner_single, Deuce_secondServe_total_lostmistake_single,
    Deuce_secondServe_total_rally_single, Deuce_secondServe_total_wonwinner_single,
    Deuce_secondserves_freq_single, Adv_secondServe_total_lostmistake_single,
    Adv_secondServe_total_rally_single, Adv_secondServe_total_wonwinner_single,
    Adv_secondserves_freq_single, secondserve_rally_single, secondserve_won_single, totalreturn_eff_single,
    firstReturn_total_lostmistake_single, firstReturn_total_rally_single, firstReturn_total_wonwinner_single,
    deuce_firstReturn_total_lostmistake_single, deuce_firstReturn_total_rally_single,
    deuce_firstReturn_total_wonwinner_single, deuce_firstreturns_freq_single,
    adv_firstReturn_total_lostmistake_single, adv_firstReturn_total_rally_single,
    adv_firstReturn_total_wonwinner_single, adv_firstreturns_freq_single,
    secondReturn_total_lostmistake_single, secondReturn_total_rally_single,
    secondReturn_total_wonwinner_single, Deuce_secondReturn_total_lostmistake_single,
    Deuce_secondReturn_total_rally_single, Deuce_secondReturn_total_wonwinner_single,
    Deuce_secondreturns_freq_single, Adv_secondReturn_total_lostmistake_single,
    Adv_secondReturn_total_rally_single, Adv_secondReturn_total_wonwinner_single,
    Adv_secondreturns_freq_single, firstreturn_rally_single, rally_lostmistake_single, rally_rally_single,
    rally_wonwinner_single, rally_freq_single, up_1st_serve_single, crit_1streturnMADE_freq_single,
    noncrit_1streturnMADE_freq_single, up_1st_return_single, crit_secondserve_freq_single,
    noncrit_2ndserve_freq_single, crit_2ndservenonloss_freq_single, noncrit_2ndservenonloss_freq_single,
    up_2nd_serve_single, crit_2ndreturnHIT_freq_single, noncrit_2ndreturnHIT_freq_single,
    criticalPercentage2ndReturns_single, noncrit_2ndreturnMADE_freq_single, up_2nd_return_single,
    FirstReturn_FH_Freq_single, FirstReturn_BH_Freq_single, FirstReturn_Slice_Freq_single,
    SecondReturn_FH_Freq_single, SecondReturn_BH_Freq_single, SecondReturn_Slice_Freq_single,
    ) = stat_func(d1_2)

    single_result = gen_out(df, "single", serve_won_single, serve_lost_single, return_won_single, return_lost_single, won_single,
                lost_single, rally_324_won_single, rally_324_lost_single, rally_5plus_won_single, rally_5plus_lost_single,
                totalserve_eff_single, return_eff_freq_single, rally_eff_freq_single, firstserverate_single,
                firstserve_eff_single, secondserve_eff_single, df_rate_single, secondserves_freq_single,
                crit_totalserve_freq_single, crit_1stserve_freq_single, noncrit_1stserve_freq_single,
                noncrit_totalserve_freq_single, breakball_allserves_single, breakball_1stserverate_single,
                deuce_allserves_freq_single, adv_allserves_freq_single, firstserves_freq_single,
                deuce_firstserves_rate_single, adv_firstserves_rate_single, firstserve_serveonly_freq_single,
                firstserve_serveFH_freq_single, firstserve_serveBH_freq_single, serveplusplayed_single,
                FH_of_ServePlus1_single, firstserve_serveFH_eff_single, BH_of_ServePlus1_single,
                firstserve_serveBH_eff_single, Slice_of_ServePlus1_single, firstserve_serveSlice_eff_single,
                secondserve_serveonly_freq_single, secondserve_serveFH_freq_single, secondserve_serveBH_freq_single,
                FH_of_ServePlus1_2nd_single, secondserve_serveFH_eff_single, BH_of_ServePlus1_2nd_single,
                secondserve_serveBH_eff_single, Slice_of_ServePlus1_2nd_single, secondserve_serveSlice_eff_single,
                firstreturn_rate_single, secondreturn_rate_single, secondreturns_freq_single, firstreturns_freq_single,
                firstreturn_eff_single, secondreturn_eff_single, Total_Returns_single, FH_Return_prop_single,
                BH_Return_prop_single, Slice_Return_prop_single, FirstReturn_FH_prop_single, FirstReturn_BH_prop_single,
                FirstReturn_Slice_prop_single, FirstReturn_FH_Eff_single, FirstReturn_BH_Eff_single,
                FirstReturn_Slice_Eff_single, SecondReturn_FH_prop_single, SecondReturn_BH_prop_single,
                SecondReturn_Slice_prop_single, SecondReturn_FH_Eff_single, SecondReturn_BH_Eff_single,
                SecondReturn_Slice_Eff_single, rally_points_single, rally_eff_single, rally_win_balance_single,
                rally_win_balance2_single, rally_length_single, All_shots_single, FH_prop_single, BH_prop_single,
                Slice_prop_single, Volley_prop_single, OH_prop_single, FH_eff_single, FH_shots_single,
                FH_WinBalance2_single, FH_WinBalance_single, BH_eff_single, BH_shots_single, BH_WinBalance2_single,
                BH_RallyRate_single, BH_WinBalance_single, Slice_eff_single, Slice_shots_single, Slice_LossRate_single,
                Slice_WinBalance2_single, firstserve_lost_single, firstserve_rally_single, firstserve_won_single,
                firstservesOnlyProp_single, dfs_single, secondServe_total_lostwinner_single,
                secondServe_total_lostforced_single, secondServe_total_lostmistake_single, secondserve_lost_single,
                crit_nonbreakball_allserves_single, crit_nonbreakball_1stserverate_single, firstreturn_lost_single,
                firstreturn_won_single, secondreturn_lost_single, secondreturn_won_single, secondreturn_rally_single,
                crit_1streturnHIT_freq_single, noncrit_1streturnHIT_freq_single, rally_prop_single, FH_ratio_single,
                BH_Slice_ratio_single, ptsplayed_single, Won_thru_Winner_single, Lost_thru_Mistake_single,
                firstServe_total_lostmistake_single, firstServe_total_rally_single, firstServe_total_wonwinner_single,
                deuce_firstServe_total_lostmistake_single, deuce_firstServe_total_rally_single,
                deuce_firstServe_total_wonwinner_single, deuce_firstserves_freq_single,
                adv_firstServe_total_lostmistake_single, adv_firstServe_total_rally_single,
                adv_firstServe_total_wonwinner_single, adv_firstserves_freq_single, secondServe_total_rally_single,
                secondServe_total_wonwinner_single, Deuce_secondServe_total_lostmistake_single,
                Deuce_secondServe_total_rally_single, Deuce_secondServe_total_wonwinner_single,
                Deuce_secondserves_freq_single, Adv_secondServe_total_lostmistake_single,
                Adv_secondServe_total_rally_single, Adv_secondServe_total_wonwinner_single, Adv_secondserves_freq_single,
                secondserve_rally_single, secondserve_won_single, totalreturn_eff_single,
                firstReturn_total_lostmistake_single, firstReturn_total_rally_single, firstReturn_total_wonwinner_single,
                deuce_firstReturn_total_lostmistake_single, deuce_firstReturn_total_rally_single,
                deuce_firstReturn_total_wonwinner_single, deuce_firstreturns_freq_single,
                adv_firstReturn_total_lostmistake_single, adv_firstReturn_total_rally_single,
                adv_firstReturn_total_wonwinner_single, adv_firstreturns_freq_single, secondReturn_total_lostmistake_single,
                secondReturn_total_rally_single, secondReturn_total_wonwinner_single,
                Deuce_secondReturn_total_lostmistake_single, Deuce_secondReturn_total_rally_single,
                Deuce_secondReturn_total_wonwinner_single, Deuce_secondreturns_freq_single,
                Adv_secondReturn_total_lostmistake_single, Adv_secondReturn_total_rally_single,
                Adv_secondReturn_total_wonwinner_single, Adv_secondreturns_freq_single, firstreturn_rally_single,
                rally_lostmistake_single, rally_rally_single, rally_wonwinner_single, rally_freq_single,
                up_1st_serve_single, crit_1streturnMADE_freq_single, noncrit_1streturnMADE_freq_single,
                up_1st_return_single, crit_secondserve_freq_single, noncrit_2ndserve_freq_single,
                crit_2ndservenonloss_freq_single, noncrit_2ndservenonloss_freq_single, up_2nd_serve_single,
                crit_2ndreturnHIT_freq_single, noncrit_2ndreturnHIT_freq_single, criticalPercentage2ndReturns_single,
                noncrit_2ndreturnMADE_freq_single, up_2nd_return_single, FirstReturn_FH_Freq_single, FirstReturn_BH_Freq_single, 
                FirstReturn_Slice_Freq_single, SecondReturn_FH_Freq_single, SecondReturn_BH_Freq_single, SecondReturn_Slice_Freq_single, d1_2)

    # Save summary
    with open(f'{zip_name}_MatchAnalysis.json', 'w') as outfile:
        json.dump(single_result, outfile, indent=4)

    print("Summarisation complete.")